// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransporteEscolar.Relatorios.Infrastructure.Persistence.Context;

#nullable disable

namespace TransporteEscolar.Relatorios.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(RelatoriosDbContext))]
    [Migration("20260621182034_InitialMariaDb")]
    partial class InitialMariaDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TransporteEscolar.Relatorios.Domain.Entities.AlunoSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("ExternalId")
                        .HasColumnType("bigint");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("alunos_snapshot", (string)null);
                });

            modelBuilder.Entity("TransporteEscolar.Relatorios.Domain.Entities.PresencaHistorica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AlunoId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("CancelouPresenca")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ConfirmouPresenca")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DataCancelamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataConfirmacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EnderecoUtilizado")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("AlunoId", "Data")
                        .IsUnique();

                    b.ToTable("presencas_historicas", (string)null);
                });

            modelBuilder.Entity("TransporteEscolar.Relatorios.Domain.Entities.RotaHistorica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<decimal>("DistanciaKm")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("QuantidadeAlunosTransportados")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("rotas_historicas", (string)null);
                });

            modelBuilder.Entity("TransporteEscolar.Relatorios.Domain.Entities.SolicitacaoRelatorio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("Ano")
                        .HasColumnType("int");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ConcluidoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Erro")
                        .HasMaxLength(2000)
                        .HasColumnType("varchar(2000)");

                    b.Property<DateTime?>("IniciadoEm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Mes")
                        .HasColumnType("int");

                    b.Property<string>("PapelSolicitante")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<long?>("ProfileIdSolicitante")
                        .HasColumnType("bigint");

                    b.Property<string>("ResultadoJson")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Tentativas")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("CriadoEm");

                    b.HasIndex("Status");

                    b.HasIndex("ProfileIdSolicitante", "CriadoEm");

                    b.ToTable("solicitacoes_relatorio", (string)null);
                });

            modelBuilder.Entity("TransporteEscolar.Relatorios.Domain.Entities.PresencaHistorica", b =>
                {
                    b.HasOne("TransporteEscolar.Relatorios.Domain.Entities.AlunoSnapshot", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aluno");
                });
#pragma warning restore 612, 618
        }
    }
}
